In [9]:
import numpy as np

# Random 5x5 ndarray
X = np.random.rand(5, 5)

# Normalize the ndarray
normalized_X = (X - X.mean()) / X.std()

# Original / normalized
print(f"Orig:\n {X}\n")
print(f"Norm:\n {normalized_X}")

Orig:
 [[0.62106612 0.60051854 0.67705808 0.34856732 0.50980693]
 [0.53961327 0.5155036  0.01164592 0.49179507 0.71529577]
 [0.22102789 0.84253697 0.4167181  0.62184516 0.88804069]
 [0.42296376 0.07945955 0.7892689  0.79034356 0.37944059]
 [0.49201192 0.28517343 0.11288414 0.58621999 0.37590601]]

Norm:
 [[ 0.55638707  0.46684589  0.80038591 -0.63109393  0.0715476 ]
 [ 0.20143607  0.09637222 -2.09931238 -0.00694354  0.9670161 ]
 [-1.1868786   1.52150116 -0.33411004  0.55978191  1.71979488]
 [-0.30689302 -1.80379771  1.28937232  1.29405544 -0.49655601]
 [-0.00599858 -0.90734854 -1.65814178  0.40453642 -0.51195885]]
